# PRCP-1023-JohnsHopkinsCovid19

### Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Load the Data
confirmed = pd.read_csv('time_series_covid19_confirmed_global.csv')
deaths = pd.read_csv('time_series_covid19_deaths_global.csv')
recovered = pd.read_csv('time_series_covid19_recovered_global.csv')

In [3]:
#Convert Wide to Long Format
confirmed_long = confirmed.melt(
    id_vars=["Province/State", "Country/Region", "Lat", "Long"],
    var_name="Date",
    value_name="Confirmed"
)

deaths_long = deaths.melt(
    id_vars=["Province/State", "Country/Region", "Lat", "Long"],
    var_name="Date",
    value_name="Deaths"
)

recovered_long = recovered.melt(
    id_vars=["Province/State", "Country/Region", "Lat", "Long"],
    var_name="Date",
    value_name="Recovered"
)

In [4]:
#Merging the Datasets
data = confirmed_long.merge(deaths_long,
                            on=["Province/State", "Country/Region", "Lat", "Long", "Date"])

data = data.merge(recovered_long,
                  on=["Province/State", "Country/Region", "Lat", "Long", "Date"],
                  how="left")   # recovered may have missing values

In [5]:
data

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0,0,0.0
1,NaN,Albania,41.153300,20.168300,1/22/20,0,0,0.0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0,0,0.0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0,0,0.0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0,0,0.0
...,...,...,...,...,...,...,...,...
64899,NaN,West Bank and Gaza,31.952200,35.233200,9/21/20,36151,265,24428.0
64900,NaN,Western Sahara,24.215500,-12.885800,9/21/20,10,1,8.0
64901,NaN,Yemen,15.552727,48.516388,9/21/20,2028,586,1235.0
64902,NaN,Zambia,-13.133897,27.849332,9/21/20,14175,331,13629.0
64903,NaN,Zimbabwe,-19.015438,29.154857,9/21/20,7683,225,5924.0

In [6]:
#Fix Date Type
data['Date'] = pd.to_datetime(data['Date'])
data

C:\Users\arpit\AppData\Local\Temp\ipykernel_27184\528595247.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['Date'] = pd.to_datetime(data['Date'])

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0.0
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0.0
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0.0
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0.0
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0.0
...,...,...,...,...,...,...,...,...
64899,NaN,West Bank and Gaza,31.952200,35.233200,2020-09-21,36151,265,24428.0
64900,NaN,Western Sahara,24.215500,-12.885800,2020-09-21,10,1,8.0
64901,NaN,Yemen,15.552727,48.516388,2020-09-21,2028,586,1235.0
64902,NaN,Zambia,-13.133897,27.849332,2020-09-21,14175,331,13629.0
64903,NaN,Zimbabwe,-19.015438,29.154857,2020-09-21,7683,225,5924.0

In [7]:
data.isnull()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,True,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
64899,True,False,False,False,False,False,False,False
64900,True,False,False,False,False,False,False,False
64901,True,False,False,False,False,False,False,False
64902,True,False,False,False,False,False,False,False
64903,True,False,False,False,False,False,False,False

In [8]:
data.shape

(64904, 8)

In [9]:
data.isnull().sum()

Province/State    45140
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
Deaths                0
Recovered          4636
dtype: int64

In [10]:
# Province/State -> normal to be NaN (do not fill)
# Recovered -> fill with forward-fill
data["Recovered"] = data["Recovered"].fillna(method="ffill")

# If still NaN at beginning, fill with 0
data["Recovered"] = data["Recovered"].fillna(0)
data

C:\Users\arpit\AppData\Local\Temp\ipykernel_27184\2477026865.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["Recovered"] = data["Recovered"].fillna(method="ffill")

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0.0
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0.0
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0.0
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0.0
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0.0
...,...,...,...,...,...,...,...,...
64899,NaN,West Bank and Gaza,31.952200,35.233200,2020-09-21,36151,265,24428.0
64900,NaN,Western Sahara,24.215500,-12.885800,2020-09-21,10,1,8.0
64901,NaN,Yemen,15.552727,48.516388,2020-09-21,2028,586,1235.0
64902,NaN,Zambia,-13.133897,27.849332,2020-09-21,14175,331,13629.0
64903,NaN,Zimbabwe,-19.015438,29.154857,2020-09-21,7683,225,5924.0

In [11]:
data.isnull().sum()

Province/State    45140
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
Deaths                0
Recovered             0
dtype: int64

In [12]:
data.describe()

,Lat,Long,Date,Confirmed,Deaths,Recovered
count,64904.000000,64904.000000,64904,6.490400e+04,64904.000000,6.490400e+04
mean,21.076624,22.829441,2020-05-22 12:00:00,3.338211e+04,1371.317346,1.971640e+04
min,-51.796300,-135.000000,2020-01-22 00:00:00,0.000000e+00,0.000000,0.000000e+00
25%,6.611100,-15.310100,2020-03-22 18:00:00,1.200000e+01,0.000000,1.000000e+00
50%,22.820850,20.921188,2020-05-22 12:00:00,3.330000e+02,4.000000,1.680000e+02
75%,41.153300,78.962880,2020-07-22 06:00:00,3.269000e+03,66.000000,1.901000e+03
max,71.706900,178.065000,2020-09-21 00:00:00,6.856884e+06,199865.000000,4.396399e+06
std,24.857935,70.059807,NaN,2.565391e+05,8998.808313,1.483536e+05

In [13]:
data.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0.0
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0.0
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0.0
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0.0
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0.0

## EDA Part

In [14]:
# Identify column types
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = data.select_dtypes(include=['object']).columns.tolist()
datetime_cols = data.select_dtypes(include=['datetime64']).columns.tolist()

print("Numerical:", numerical_cols)
print("Categorical:", categorical_cols)
print("Datetime:", datetime_cols)

Numerical: ['Lat', 'Long', 'Confirmed', 'Deaths', 'Recovered']
Categorical: ['Province/State', 'Country/Region']
Datetime: ['Date']

In [15]:
data = data.sort_values(["Country/Region", "Date"])
data["Daily_Confirmed"] = data.groupby("Country/Region")["Confirmed"].diff().fillna(0)

target = data["Daily_Confirmed"]
features = data.drop(columns=["Daily_Confirmed"])
data

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Daily_Confirmed
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0.0,0.0
266,NaN,Afghanistan,33.939110,67.709953,2020-01-23,0,0,0.0,0.0
532,NaN,Afghanistan,33.939110,67.709953,2020-01-24,0,0,0.0,0.0
798,NaN,Afghanistan,33.939110,67.709953,2020-01-25,0,0,0.0,0.0
1064,NaN,Afghanistan,33.939110,67.709953,2020-01-26,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
63839,NaN,Zimbabwe,-19.015438,29.154857,2020-09-17,7633,224,5841.0,35.0
64105,NaN,Zimbabwe,-19.015438,29.154857,2020-09-18,7647,224,5883.0,14.0
64371,NaN,Zimbabwe,-19.015438,29.154857,2020-09-19,7672,225,5914.0,25.0
64637,NaN,Zimbabwe,-19.015438,29.154857,2020-09-20,7683,225,5924.0,11.0
64903,NaN,Zimbabwe,-19.015438,29.154857,2020-09-21,7683,225,5924.0,0.0

In [18]:
# use a for loop to find NoN Objective data type
data1 = []                         # create a empty List
for i in data.columns:             # use for loop in data.columns
    if data[i].dtype!='O':         # use if condition
        data1.append(i)            # Append that columns which satisfy the if condition
print(data1)

['Lat', 'Long', 'Date', 'Confirmed', 'Deaths', 'Recovered', 'Daily_Confirmed']

In [19]:
data1 = data[data1]                  # create a Numerical data type Variable
data2 = data.drop(data1,axis=1)